name: "PSEG Automation, Fork"
url: "https://github.com/kvarnelis/ha-pseg"
maintainer: "Eric Wasserman/Kazys Varnelis"
description: "Automated PSEG login and energy data retrieval"
version: "2.2.0"
homeassistant: "2024.8.0"
